### ISSUE TITLE
Help with implementation of eID - You cannot consume this service

### ISSUE THREAD

**Issue by KrakenTyio** [Trust1Team/t1c-lib-js#58]
Hi I have problem implement with this lib.

t1c-lib-js ver. 2.12

I already have this configuration:
```ts
 async prepareGCL(config: GCLConfigOptions) {
        try {
            const gclConfig = new GCLConfig(config);
            const client: GCLClient = await GCLClient.initialize(gclConfig);
            const readers: CardReadersResponse = await client.core().readersCardAvailable();
            if (readers.data.length) {
                return client.beid(readers.data[0].id).allData({filters: ['rn', 'address', 'picture'], parseCerts: false});
            }
        } catch (e) {
        }

        throw Error('No readers');
}
```

but always i get message 
```
No installed GCL component found. Please download and install the GCL.
```

Also Im little confused how to download GCL,
Its should lib promt to download right?

Ill implement also node api to retrieving token by api_key.
But for now i dont have clue how to download GCL in nice user way.

**Comment by KrakenTyio** [comment]
@jonasvekeman could you help me?

**Comment by KrakenTyio** [comment]
Already forward for next step
```ts
protected async prepareGCL() {

        const config: GCLConfigOptions = {
            apiKey: trust1Key,
            implicitDownload: true,
            gwOrProxyUrl: 'https://accapim.t1t.be:443',
        };

        try {
            const gclConfig = new GCLConfig(config);
            const client: GCLClient = await GCLClient.initialize(gclConfig);
            const readers: CardReadersResponse = await client.core().readersCardAvailable();
            if (readers.success && readers.data.length) {
                return client.beid(readers.data[0].id).allData({filters: ['rn', 'address', 'picture'], parseCerts: false});
            }
        } catch (e) {
            if (e instanceof T1CLibException) {
                if (e.code === '301' || e.code === '302') {
                    const download: DSDownloadLinkResponse = await e.client.download();
                }
            }
        }

        throw Error('No readers');
    }
```

but API for registered token respond "You cannot consume this service"
Someone know what its mean?

**Comment by jonasvekeman** [comment]
Dear @KrakenTyio 

You need a valid API key to get access to our backend in order to be able to download the software. We've created an API key for you in our Q&A environment: 08cec6ab-acef-4714-aace-b2aaa155ff55. The gwOrProxyUrl should indeed be set to https://accapim.t1t.be:443.

With this API key you'll be able to communicate with the Belgium eID card. If you need more functionalities, please let us know. More information and the available containers can be found at [https://t1t.gitbook.io/t1c-js-guide-v2/](https://t1t.gitbook.io/t1c-js-guide-v2/).

Normally the communication is protected by a CORS whitelist we configure on our backend. At the moment all calls are allowed, could you provide us with a list of domains we can whitelist (e.g. *.krakentyio.com)?

For a production API key, you can contact us at [sales@trust1team.com](sales@trust1team.com). You can found more detailed information and pricing at [https://www.trust1connector.com/features](https://www.trust1connector.com/features).

Kind regards,
Jonas

**Comment by KrakenTyio** [comment]
@jonasvekeman for now im using my local address
http://{some label}.{some project}.ssvidran.u.bart.sk

this key working i can now go to another step :D

**Comment by KrakenTyio** [comment]
@jonasvekeman i already download this trust1connector_amd64.deb
Is there possibility package for arch linux?
dont found AUR package and debtap after compilation and instalation raise error
`/tmp/alpm_kpAmae/.INSTALL: riadok 78`

**Comment by jonasvekeman** [comment]
Hi @KrakenTyio 

At the moment we only support Ubuntu and Debian as Linux distributions.
