### ISSUE TITLE
Card implementations never throw T1CLibException instances

### ISSUE THREAD

**Issue by benvh** [Trust1Team/t1c-lib-js#77]
The typescript definitions define that all calls will throw a T1CLibException instance if anything goes wrong. In reality card specific call simply return the connector's error response.

These two look alike, (they have code, description, ... properties) but they are not the same!
For example, T1CLibException defines the code as a string but in the connector responses these are all numbers. In light of issue 76 this does not allow for simple type checking with ```instanceof``` either.

Best to convert all these response object to actual T1CLibException instances or introduce a new Exception type conform with these responses.

**Comment by GillesPl** [comment]
Dear Ben,

We kept these Exception instances different from each other because a user/front-end mostly wants to use prettified error responses instead of the full blown stacktrace that the Trust1Connector can return if its not handled. Also this provides more control over the library, as you can see in issue #76 you can get different responses based on which api you use, unifying this in the Trust1Connector JS lib gives the integrator and end user the best experience.

Kind regards,
Gilles
